### ISSUE TITLE
depending on an uglify-es that doesn't exist?

### ISSUE THREAD

**Issue by ShawnTalbert** [ionic-team/stencil-app-starter#42] opened 2018-02-10 04:10 UTC
```
npm install @stencil/core

npm ERR! code ETARGET
npm ERR! notarget No matching version found for uglify-es@3.3.8
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of @stencil/core
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
```

**Comment by jgw96** [comment] 2018-02-19 16:32
Hello! I cannot reproduce this with the latest version of Stencil. To update you can run `npm install @stencil/core@latest --save-exact`. Because of this I will be closing this issue for now. Thanks for using Stencil!

**Closed by jgw96** 2018-02-19 16:32 UTC
